--- #YAML:1.0
name:               Object-Dependency
version:            0.31
abstract:           dependency graph
author:
    - David Muir Sharnoff <muir@idiom.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Hash::Util:       0
    List::MoreUtils:  0
    Scalar::Util:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
